version: '3.8'

services:
  facility-connect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # For development, mount the source code
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - facility-network

networks:
  facility-network:
    driver: bridge

volumes:
  node_modules:
  next_cache:
